<!-- Code generated by Gemini -->
<template>
  <span
    class="wiki-tooltip"
    @mouseenter="show"
    @mouseleave="hide"
    @touchstart.passive="handleTouchStart"
  >
    <a
      :href="wikiUrl"
      target="_blank"
      rel="noopener noreferrer"
      class="wiki-link"
      :aria-describedby="tooltipId"
      @focus="show"
      @blur="hide"
      @click="handleClick"
      >{{ displayLabel }}</a
    >
    <transition name="fade">
      <div v-if="visible" class="wiki-tooltip-content" role="tooltip" :id="tooltipId">
        <p v-if="loading" class="loading">Loading…</p>
        <p v-else-if="error" class="error">{{ error }}</p>
        <p v-else>{{ summary }}</p>
      </div>
    </transition>
  </span>
</template>

<script setup>
import { ref, computed } from "vue";

const props = defineProps({
  url: { type: String, required: true },
  label: { type: String, default: "" },
});

const visible = ref(false);
const loading = ref(false);
const error = ref("");
const summary = ref("");
const tooltipId = `wiki-tt-${Math.random().toString(36).slice(2)}`;

let hasFetched = false;
let fetchController;
let isTouch = false;

const pageTitle = computed(() => {
  try {
    if (/^https?:\/\//.test(props.url)) {
      const u = new URL(props.url);
      const parts = u.pathname.split("/");
      return decodeURIComponent(parts.pop() || "");
    }
    return props.url;
  } catch {
    return props.url;
  }
});

const wikiUrl = computed(() => {
  if (/^https?:\/\//.test(props.url)) {
    return props.url;
  }
  return `https://en.wikipedia.org/wiki/${encodeURIComponent(pageTitle.value)}`;
});

const displayLabel = computed(() => props.label || pageTitle.value.replace(/_/g, " "));

async function fetchSummary() {
  if (hasFetched) return;
  loading.value = true;
  error.value = "";
  fetchController = new AbortController();
  const apiUrl = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(
    pageTitle.value
  )}`;
  
  try {
    const res = await fetch(apiUrl, { signal: fetchController.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    const extract = data.extract || "";
    const match = extract.match(/^[^.!?]*[.!?]/);
    summary.value = match
      ? match[0]
      : extract.split(/\.(\s|$)/)[0] + (extract.includes(".") ? "." : "");
    hasFetched = true;
  } catch (e) {
    if (e.name !== "AbortError") {
      error.value = "Failed to load summary.";
    }
  } finally {
    loading.value = false;
  }
}

function show() {
  visible.value = true;
  if (!hasFetched) {
    fetchSummary();
  }
}

function hide() {
  visible.value = false;
}

function handleTouchStart() {
  isTouch = true;
}

function handleClick(event) {
  if (isTouch && !visible.value) {
    event.preventDefault();
    show();
  }
}
</script>

<style scoped>
.wiki-tooltip {
  position: relative;
  display: inline-block;
}
.wiki-link {
  text-decoration: underline dotted;
  cursor: help;
}
.wiki-tooltip-content {
  position: absolute;
  z-index: 20;
  bottom: calc(100% + 8px);
  left: 50%;
  transform: translateX(-50%);
  width: 300px;
  max-width: 80vw;
  background: var(--vp-c-bg-soft);
  color: var(--vp-c-text-1);
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  padding: 12px 16px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  font-size: 0.875rem;
  line-height: 1.4;
}
.loading {
  opacity: 0.7;
  font-style: italic;
}
.error {
  color: #c22;
}
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateX(-50%) translateY(4px);
}

@media (max-width: 640px) {
  .wiki-tooltip-content {
    position: fixed;
    bottom: auto;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 90vw;
    max-width: 400px;
  }
}

@media (prefers-color-scheme: dark) {
  .wiki-tooltip-content {
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
  }
}
</style>
